name: Auto-build and push

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "37 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: arm64
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and push
        run: $GITHUB_WORKSPACE/build.sh
