name: Auto-build and push

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "last-update.txt" ]
  schedule:
    - cron: "37 21 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and push
        run: $GITHUB_WORKSPACE/build.sh

      - name: Create last update file
        run: date > last-update.txt

      - name: Commit last-update.txt
        run: |
          git config --global user.name "Przemysław Buczkowski"
          git config --global user.email "przemub@users.noreply.github.com"
          git add last-update.txt
          git commit -m "Auto-update last-update.txt" last-update.txt
          git push

